default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-vcs-permalinks
      - id: debug-statements
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: no-commit-to-branch
      - id: name-tests-test
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.7.1
    hooks:
      - id: reorder-python-imports
  # Need deactivate as something is going horribly wrong inside Jake :'(
  # args: "-w" doesn't work either since it's Jake itself crashing and returning nonzero
  # - repo: https://github.com/sonatype-nexus-community/jake
  #   rev: "v1.4.3"
  #   hooks:
  #     - id: scan
  - repo: https://github.com/returntocorp/semgrep
    rev: "v0.82.0"
    hooks:
      - id: semgrep
        args:
          ["--config", "auto", "--error", "--skip-unknown-extensions", "src"]
