default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
     - id: trailing-whitespace
     - id: end-of-file-fixer
     - id: mixed-line-ending
     - id: check-yaml
     - id: check-toml
     - id: check-json
     - id: check-added-large-files
     - id: check-case-conflict
     - id: check-docstring-first
     - id: check-ast
     - id: check-executables-have-shebangs
     - id: check-vcs-permalinks
     - id: debug-statements
     - id: detect-aws-credentials
     - id: detect-private-key
     - id: forbid-new-submodules
     - id: no-commit-to-branch
     - id: name-tests-test
     - id: pretty-format-json
       args: [ --autofix ]
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
