
name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: vinomaster/mkdocs-ghpages-docker-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
